### ISSUE TITLE
ENOENT: no such file or directory tmp/../vendor/.bin/indent-string

### ISSUE THREAD

**Issue by raucao** [adopted-ember-addons/broccoli-sass-source-maps#12]
I have an issue with multiple apps using `ember-cli-sass` and the latest versions of all of node, npm, libsass and this library (via updated ember-cli-sass). I tried everything I could come up with in order to fix it, but it keeps failing with the follow stack trace, whenever I try to build and/or watch one of these apps:

```
~/src/remotestorage/apps/dashtab $ ember build
Future versions of Ember CLI will not support v5.0.0. Please update to Node 0.12 or io.js.
version: 1.13.8
Build failed.
ENOENT: no such file or directory, stat '/home/basti/src/remotestorage/apps/dashtab/tmp/sass_compiler-input_base_path-VTbfcUKS.tmp/0/vendor/.bin/indent-string'
Error: ENOENT: no such file or directory, stat '/home/basti/src/remotestorage/apps/dashtab/tmp/sass_compiler-input_base_path-VTbfcUKS.tmp/0/vendor/.bin/indent-string'
    at Error (native)
    at Object.fs.statSync (fs.js:892:18)
    at SassCompiler.keyForFile (/home/basti/src/remotestorage/apps/dashtab/node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/index.js:91:55)
    at Array.map (native)
    at SassCompiler.CachingWriter._conditionalBuild (/home/basti/src/remotestorage/apps/dashtab/node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/index.js:107:61)
    at /home/basti/src/remotestorage/apps/dashtab/node_modules/broccoli-sass-source-maps/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/home/basti/src/remotestorage/apps/dashtab/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/home/basti/src/remotestorage/apps/dashtab/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/home/basti/src/remotestorage/apps/dashtab/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/home/basti/src/remotestorage/apps/dashtab/node_modules/rsvp/dist/rsvp.js:1198:9)
```

[deleted]

indent-string in that dir exists, but seems to be a wrong symlink:

```
tmp/sass_compiler-input_base_path-oemkgqKh.tmp/0/vendor/.bin/indent-string -> ../indent-string/cli.js
```

Update: the whole library seems to be present in the linked directory, but it only contains an `index.js` and no `cli.js`.

Update 2: This happened in July: https://github.com/sindresorhus/indent-string/commit/4322f1ad7e236f5bdab83d5d5b97d2c89cfd0827

**Comment by simonexmachina** [comment]
I think maybe @stefanpenner may know something about this problem?

**Comment by raucao** [comment]
Forgot to add: looks like multiple nested deps too loosely defined and the last one not using SemVer correctly. I have no idea how to fix my stuff, though.

**Comment by simonexmachina** [comment]
Closing due to inactivity, feel free to reopen.
