### ISSUE TITLE
Build with npm 6.x are broken

### ISSUE THREAD

**Issue by Dirk-27** [adopted-ember-addons/broccoli-sass-source-maps#60]
This commit https://github.com/adopted-ember-addons/broccoli-sass-source-maps/commit/ec0afe2eec36618207818279ce8a8b99915f97b4 breaks our builds we have to do with npm version 6.14.16

The error is: 

```
ERROR Summary:
  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Unexpected token '?'
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Unexpected token '?'
  - name: SyntaxError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: /builds/educube/nextclassroom/node_modules/broccoli-sass-source-maps/index.js:62
      sourceMapIncludeSources: options.sourceMapIncludeSources ?? true,
                                                                ^
SyntaxError: Unexpected token '?'
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/builds/educube/nextclassroom/node_modules/ember-cli-sass/index.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
```

**Comment by Dirk-27** [comment]
#61 will fix it for us. Thanks so far, we are looking forward to get the solution with release 4.2.3 soon.

**Comment by Dirk-27** [comment]
Thank you! It's working again!
